Repository BuggyPeasy/WebClient, pull requests merged in 2023-09, with the labels that each got.

#15 Added Tests for AnswerForm Component
  .eslintrc.json
  public/index.html
  src/AnswerForm.test.ts
  src/AnswerForm.ts
Labels: test

#20 Added SSH Key Configuration Tutorial to README.md
  README.md
Labels: documentation

#17 Set up deploy env
  Dockerfile
  package-lock.json
  package.json
Labels: deploy

#21 Implemented AnswerForm
  .eslintrc.json
  public/index.html
  src/AnswerForm.test.ts
  src/AnswerForm.ts
Labels: dev

#26 Changed append to appendChild
  src/AnswerForm.test.ts
  src/SearchBar.test.ts
Labels: bug

#27 Set up bun to replace npm
  .eslintrc.json
  .github/workflows/action.yml
  .gitignore
  README.md
  bun.lockb
  bunfig.toml
  index.test.ts
  jest.config.js
  package-lock.json
  package.json
  tests/AnswerForm.test.ts
  tests/SearchBar.test.ts
  tsconfig.eslint.json
  tsconfig.json
Labels: deploy

#30 Finished Tests for ImageContainer
  src/ImageContainer.ts
  tests/ImageContainer.test.ts
  tests/SearchBar.test.ts
Labels: test

#31 Finished tests for EditableText
  src/EditableText.ts
  tests/EditableText.test.ts
Labels: test

#32 Added tests for NavItem
  bun.lockb
  src/NavItem.ts
  tests/NavItem.test.ts
Labels: test

#34 Finished Implementing EditableText
  public/index.html
  src/EditableText.ts
  tests/EditableText.test.ts
Labels: dev

#33 Finished ImageContainer
  src/ImageContainer.ts
  tests/ImageContainer.test.ts
Labels: dev

#36 Set up Firebase Dev Environment #35
  .firebaserc
  .github/workflows/dev.yml
  .github/workflows/main.yml
  .gitignore
  README.md
  bun.lockb
  firebase.json
  firebase/Dev.ts
  firebase/Prod.ts
  package.json
  public/404.html
  public/index.html
Labels: deploy

#37 Finished NavItem
  public/index.html
  src/ImageContainer.ts
  src/NavItem.ts
  tests/ImageContainer.test.ts
  tests/NavItem.test.ts
Labels: dev
